Applying patches of the new commits from both c and odbc connectors.
Summary:
The following commits are added:
In particular, it has a fix for the issue https://jira.mariadb.org/projects/ODBC/issues/ODBC-289
which was also hit by one of our customers.

Don't define uchar if my_global.h was previously included (server build)

MDEV-19237 - do not resend prepared statement metadata unnecessarily

fix warnings

Updating underlying libmariadb to v3.1.10

Minor change in FindDM script

Add option to define doc and license install dir

License dir is the same as the doc dir by default

Fix for the previous merge

Plus running own install.cmake before running C/C's cmake to take
control over where things are getting installed.
Made (default) lib installation path depending on INSTALL_LIB_SUFFIX

Fix implicit declarations on Linux

ma_debug.c:47:5: warning: implicit declaration of function 'fwprintf'; did you mean 'fprintf'?
ma_dsn.c:284:15: warning: implicit declaration of function 'strcasestr'; did you mean 'strcasecmp'?
ma_common.c:45:17: warning: implicit declaration of function 'iswspace'

Surround multiline macros

ma_helper.h:97:3: warning: macro expands to multiple statements [-Wmultistatement-macros]
   97 |   free((a));\
      |   ^~~~
ma_string.c:387:5: note: in expansion of macro 'MADB_FREE'
  387 |     MADB_FREE(StmtStr);
      |     ^~~~~~~~~
ma_string.c:386:3: note: some parts of macro expansion are not guarded by this 'if' clause
  386 |   if (StmtStr)
      |   ^~

ma_error.h:163:3: warning: macro expands to multiple statements [-Wmultistatement-macros]
  163 |   strcpy_s((a)->SqlState, SQL_SQLSTATE_SIZE+1, MADB_ErrorList[MADB_ERR_00000].SqlState); \
      |   ^~~~~~~~
ma_platform_posix.c:256:5: note: in expansion of macro 'MADB_CLEAR_ERROR'
  256 |     MADB_CLEAR_ERROR(Error);
      |     ^~~~~~~~~~~~~~~~
ma_platform_posix.c:255:3: note: some parts of macro expansion are not guarded by this 'if' clause
  255 |   if (Error)
      |   ^~

Fix initializer type for MADB_ErrorList

The initializer { 0, 0, 0, -1 } results in an error entry of,
 {SqlState = "\000\000\000\377\000",
  SqlStateV2 = "\000\000\000\000\000",
  SqlErrorMsg = '\000' <repeats 512 times>,
  ReturnValue = 0}

The reason is that integers are converted to char initializers in the
SqlState char array and the remainder is set to 0. Instead, we should
use compatible types so no implicit conversion occurs. With this, the
entry becomes,

 {SqlState = "\000\000\000\000\000",
  SqlStateV2 = "\000\000\000\000\000",
  SqlErrorMsg = '\000' <repeats 512 times>,
  ReturnValue = -1}

ODBC-202 Added iconv-based conversion function for non-Windows

Basically it's been moved and renamed from C/C, that doesn't want to
have it any more.
Removed dependency on mariadbclient from tests - it was needed only for
charset conversions.

ODBC-289 Possible crash in case of array fetch

In case of reexecuting fetch was possible when old bind is already
freed, and newly allocated bind structures have not been bound yet.
Fix of tests on windows in addition to previous commit

ODBC-288 Added the connection option INTERACTIVE to tell server to use

interactive timeout. Added the testcase.

Not exactly ODBC-290, but made Force Forwar Only Cursor it default

cursor type for statements.
Also added the field to this option to the setup dialog and added
FORWARDONLY individual name for that option(along with OPTIONS's bit
And a small fix for the previous commit(interactive).

Test Plan:
manually tested and built
It builds from scratch and the queries are running.

Reviewers: iblinov-ua, amakarovych-ua

Reviewed By: amakarovych-ua

Subscribers: adam, vtkachuk-ua, engineering-list, carl

Differential Revision: https://grizzly.internal.memcompute.com/D42842